model:
  architecture: 'allconv_01'
  audio_inputs: True

datasets:
  names: ['emma_gems9']

features:
  frame_rate: 5
  window_size: 8192
  sample_rate: 44100
  freq_bins: 200

training:
  learning_rate: 1e-1
  sequence_length: 150
  sequence_hop: 50
  k_samples: 1e5
  batch_size: 32
  validation_size: 0.5
  memory_map: True
  num_data_threads: 8
  max_num_epochs: 999999
  patience: 10
  refinements: 3
