datasets:
  dense_weight_alpha: 2
  labels:
  - Sadness
  loss_func: dense_weight
  names:
  - emma_gems9
  oversampling: true
  oversampling_ratio: 1
  oversampling_tolerance: 0.5
  oversampling_method: 'density_oversampling'
  scale: None
features:
  frame_rate: 5
  freq_bins: 200
  sample_rate: 44100
  window_size: 8192
model:
  architecture: allconv_01
  audio_inputs: true
training:
  batch_size: 50
  k_samples: 1e5
  learning_rate: 1e-2
  max_num_epochs: 999999
  memory_map: true
  num_data_threads: 8
  patience: 30
  refinements: 3
  sequence_hop: 40
  sequence_length: 150
  transformation: None
  validation_size: 0.5
